CREATE DATABASE IF NOT EXISTS akvo_app;
USE akvo_app;

CREATE TABLE IF NOT EXISTS diagnosticos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  empresa_nombre VARCHAR(255) NOT NULL,
  etapa_negocio VARCHAR(120) DEFAULT NULL,
  financiera DECIMAL(5,2) DEFAULT 0,
  contable DECIMAL(5,2) DEFAULT 0,
  procesos DECIMAL(5,2) DEFAULT 0,
  digital DECIMAL(5,2) DEFAULT 0,
  estrategia DECIMAL(5,2) DEFAULT 0,
  total_score DECIMAL(5,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
